services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: drrkobe
      POSTGRES_USER: drrkobe
      POSTGRES_PASSWORD: QajcSAVYF3iErlQF6SJ/aj5kd9k31stTvDL/tlwRnyr5MO57
    volumes:
      - drrkobe_postgres:/var/lib/postgresql/data
    networks:
      - drrkobe
    mem_limit: 1g
    cpus: 0.75

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - drrkobe_redis:/data
    networks:
      - drrkobe
    mem_limit: 256m
    cpus: 0.25

  composer:
    image: composer:2
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - drrkobe

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
      - redis
    networks:
      - drrkobe
      - proxy
    mem_limit: 1g
    cpus: 0.75

networks:
  drrkobe:
    driver: bridge

  proxy:
    external: true

volumes:
  drrkobe_postgres:
  drrkobe_redis:
